# Generated by Django 3.1.2 on 2020-10-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
