# Generated by Django 3.1.2 on 2020-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_post_link_contain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('post', models.ManyToManyField(to='User.Post')),
            ],
        ),
    ]
