# Generated by Django 3.1.2 on 2020-10-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_count',
            field=models.IntegerField(null=True),
        ),
    ]
